import toml

# Load the secrets from the TOML file
secrets = toml.load("secrets.toml")

# Access specific secrets
db_user = secrets["database"]["user"]
aws_access_key = secrets["aws"]["access_key"]
